import { ArrowUpRight, FolderKanban, ListFilter, Plus, Search, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router";

import type { Route } from "./+types/projects";
import { HealthPill, PageHeading, PortalShell, TagBadge } from "../portal/PortalShell";
import { employees, projects } from "../portal/portal-data";

export function meta(_: Route.MetaArgs) {
	return [{ title: "Projects · Jonverk Portal" }, { name: "description", content: "Every active JonVerk project and its shared workboard." }];
}

export default function Projects() {
	const [filter, setFilter] = useState<"all" | "on-track" | "at-risk">("all");
	const [query, setQuery] = useState("");
	const visibleProjects = useMemo(() => projects.filter((project) => (filter === "all" || project.health === filter) && `${project.name} ${project.code}`.toLowerCase().includes(query.toLowerCase())), [filter, query]);

	return <PortalShell><PageHeading eyebrow="Workspace / Projects" title="Projects" description="Every project has a brief, a living spec, a shared board, and a place for the decisions that shape it." action={<button className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#202126] px-4 text-xs font-semibold text-white shadow-sm transition hover:bg-black"><Plus size={15} /> New project</button>} />
		<div className="mt-8 flex flex-col gap-3 rounded-2xl border border-[#e1e3e8] bg-white p-3 sm:flex-row sm:items-center sm:justify-between sm:p-4"><div className="flex items-center gap-2 text-xs font-semibold text-[#70747f]"><FolderKanban size={16} className="text-[#756ad9]" /> 3 active project workspaces</div><div className="flex flex-col gap-2 sm:flex-row"><label className="flex h-9 items-center gap-2 rounded-xl border border-[#e5e6ea] bg-[#fafafa] px-3 text-xs text-[#a0a3ab]" htmlFor="project-search"><Search size={14} /><input id="project-search" value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent outline-none placeholder:text-[#a0a3ab] sm:w-44" placeholder="Search projects" /></label><div className="flex gap-1 rounded-xl bg-[#f4f4f6] p-1"><button onClick={() => setFilter("all")} className={`rounded-lg px-3 py-1.5 text-[10px] font-semibold ${filter === "all" ? "bg-white text-[#4f52a0] shadow-sm" : "text-[#9296a1]"}`}>All</button><button onClick={() => setFilter("on-track")} className={`rounded-lg px-3 py-1.5 text-[10px] font-semibold ${filter === "on-track" ? "bg-white text-[#4f52a0] shadow-sm" : "text-[#9296a1]"}`}>On track</button><button onClick={() => setFilter("at-risk")} className={`rounded-lg px-3 py-1.5 text-[10px] font-semibold ${filter === "at-risk" ? "bg-white text-[#4f52a0] shadow-sm" : "text-[#9296a1]"}`}>At risk</button></div></div></div>
		<div className="mt-5 grid gap-4 xl:grid-cols-2">{visibleProjects.map((project) => { const owner = employees.find((employee) => employee.tag === project.owner) ?? employees[0]; return <Link to={`/projects/${project.id}`} key={project.id} className="group rounded-2xl border border-[#e1e3e8] bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#c9c5fa] hover:shadow-lg hover:shadow-[#574fc5]/5 sm:p-6"><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-start gap-3"><span className="mt-0.5 h-3 w-3 shrink-0 rounded-full" style={{ backgroundColor: project.accent }} /><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#a0a3ac]">{project.code}</p><h2 className="mt-1 truncate text-lg font-semibold tracking-[-0.03em]">{project.name}</h2></div></div><ArrowUpRight size={17} className="shrink-0 text-[#b0b3bc] transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-[#7166d4]" /></div><p className="mt-4 min-h-10 text-xs leading-5 text-[#818590]">{project.description}</p><div className="mt-5 flex flex-wrap items-center gap-2"><HealthPill health={project.health} /><span className="rounded-full bg-[#f4f4f6] px-2.5 py-1 text-[10px] font-semibold text-[#7d818b]">Phase {project.phaseNumber} · {project.phase}</span><span className="ml-auto text-[10px] text-[#a0a3ac]">Updated {project.updated}</span></div><div className="mt-5 border-t border-[#eff0f2] pt-4"><div className="flex items-center justify-between text-[10px] font-semibold text-[#777b86]"><span>Progress</span><span>{project.progress}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#f0f1f3]"><div className="h-full rounded-full" style={{ width: `${project.progress}%`, backgroundColor: project.accent }} /></div></div><div className="mt-5 flex items-center justify-between"><TagBadge tag={owner.tag} kind={owner.kind} color={owner.color} /><span className="flex items-center gap-1.5 text-[10px] text-[#9498a2]"><Users size={13} /> {project.tasks.length} board tasks</span></div></Link>})}</div>
		{visibleProjects.length === 0 && <div className="mt-5 rounded-2xl border border-dashed border-[#d9dbe1] bg-white py-16 text-center"><ListFilter className="mx-auto text-[#a3a6af]" size={20} /><p className="mt-3 text-sm font-semibold">No projects match that view.</p><p className="mt-1 text-xs text-[#91949e]">Try a different health filter or search phrase.</p></div>}
	</PortalShell>;
}
